### PR TITLE
Add Pagination, Fix env TOKEN reference from readme, allow wildcard cdn domains

### PR DESCRIPTION
**Pull request by CarrettaRiccardo**
- add pagination to feed query
- fix broken reference from README of env token (README showed `env.INSTAGRAM_TOKEN` while code used `env.IG_TOKEN`) -> make it `env.NEXT_PUBLIC_INSTAGRAM_TOKEN` and using a client component
- support all Instagram cdn domains using `hostname: "*.cdninstagram.com"` in `next.config` instead of only `scontent.cdninstagram.com`

### CODE REVIEW

**Review by jrparente — COMMENTED** [review]
Hi Riccardo,

Thanks for the work on implementing pagination for the Instagram feed! This looks awesome and very well-organized! 

I have only a question about the logic used to update the feed data with new entries. In the part where we update the state of instagramFeed:

```
setInstagramFeed(prevFeed => {
  if (prevFeed && prevFeed.data.length > 0) {
    return {
      ...feed,
      data: [...prevFeed.data, ...feed.data]
    };
  }
  return feed;
});
```

Could you help me understand how this approach ensures that we do not end up adding duplicate photos to the feed, especially when loading more items? I want to make sure that each batch of photos loaded is unique and that we’re not displaying the same photos repeatedly.

Looking forward to your insights!

Best,
Joana

**Comment by we-ink** [comment]
Every time a fetch is made to the instagram api, a `after` cursor is returned.
Saving this cursor and appending it to the next fetch, assures that returned data only follows the previous cursor, therefore never replicating posts.

Think of cursors as indicators of a specific item in a list, they are used in the same logic as `skip` in pagination/query, but are safer because by referencing a specific item, you cover all those edge cases where the list length changes while you are querying different pages.

The `setInstagramFeed` just keeps the previous data post list, while adding the new posts (in `data: [...prevFeed.data, ...feed.data]`) and replacing other returned data (in `...feed`).
This is just a way to preserve all data returned from the api, not only the posts, in case of needing other info or for future extensions ;)
The `after` cursor is saved in a separate variable for clarity.

Hope my description is clear!

**Comment by CarrettaRiccardo** [comment]
Every time a fetch is made to the instagram api, a `after` cursor is returned.
Saving this cursor and appending it to the next fetch, assures that returned data only follows the previous cursor, therefore never replicating posts.

Think of cursors as indicators of a specific item in a list, they are used in the same logic as `skip` in pagination/query, but are safer because by referencing a specific item, you cover all those edge cases where the list length changes while you are querying different pages.

The `setInstagramFeed` just keeps the previous data post list, while adding the new posts (in `data: [...prevFeed.data, ...feed.data]`) and replacing other returned data (in `...feed`).
This is just a way to preserve all data returned from the api, not only the posts, in case of needing other info or for future extensions ;)
The `after` cursor is saved in a separate variable for clarity.

Hope my description is clear!

**Comment by jrparente** [comment]
Hi Riccardo,

Thank you for the detailed explanation! It's very clear! :)

I'm going to merge this now. Thanks!
Joana

**Pull request merged**
